### ISSUE TITLE
Flatpak Not Building

### ISSUE THREAD

**Issue by yanike** [electron-forge/electron-forge-docs#44]
```
sh-5.1$ flatpak-spawn --host yarn make
yarn run v1.22.5                                                                                                       
$ electron-forge make                                                                                                  
✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets: flatpak
✖ Making for target: flatpak - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: flatpak
flatpak failed with status code 1
Error: flatpak failed with status code 1
    at ChildProcess.child.on (../node_modules/@malept/flatpak-bundler/index.js:71:16)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
error Command failed with exit code 1.                                                                                 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.  
```

**Comment by malept** [comment]
This issue tracker is not meant for folks to ask questions about Electron Forge usage.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
